apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80 # Must be same as the deployment's container port . See deployment.yaml
  selector:
    app: nginx-deployment
