apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s-web-deployment
        image: djangok8s.azurecr.io/webapp:latest
        envFrom:
          - secretRef:
              name: django-k8s-web-prod-env
        env:
          - name: PORT
            value: "8001"
        ports:
          - containerPort: 8001
      imagePullSecrets:
        - name: djangok8s-acr-secret

---

apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8001 # Must be same as the deployment's container port . See deployment.yaml
  selector:
    app: django-k8s-web-deployment
